<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import { authApi, type User } from '@/api/services'
import { useSession } from '@/composables/session'
const router = useRouter(); const { clear, setUser } = useSession(); const profile = ref<User>(); const contact = reactive({ phone: '', email: '' }); const password = reactive({ currentPassword: '', newPassword: '', confirmPassword: '' }); const saving = ref(false)
const saveContact = async () => { if (!profile.value) return; saving.value = true; try { const user = await authApi.updateMe({ nickname: profile.value.nickname, avatarUrl: profile.value.avatarUrl, phone: contact.phone, email: contact.email }); profile.value = user; setUser(user); ElMessage.success('联系方式已更新') } finally { saving.value = false } }
const savePassword = async () => { if (password.newPassword !== password.confirmPassword) return ElMessage.warning('两次输入的新密码不一致'); saving.value = true; try { await authApi.changePassword({ currentPassword: password.currentPassword, newPassword: password.newPassword }); ElMessage.success('密码已修改，请重新登录'); clear(); router.replace('/auth') } finally { saving.value = false } }
const logout = async () => { try { await ElMessageBox.confirm('确认退出当前账号吗？', '退出登录') } catch { return } clear(); router.replace('/auth') }
onMounted(async () => { profile.value = await authApi.me(); contact.phone = profile.value.phone || ''; contact.email = profile.value.email || '' })
</script>
<template><div class="shell page personal-layout"><aside class="personal-nav"><h3>个人中心</h3><RouterLink to="/profile">个人资料</RouterLink><RouterLink to="/orders">我的订单</RouterLink><RouterLink to="/addresses">收货地址</RouterLink><RouterLink to="/account" class="selected">账户安全</RouterLink></aside><section class="profile-content"><h1>账户安全</h1><div class="security-grid"><article><h2>联系方式</h2><p>手机号和邮箱用于账户识别与订单联系。</p><el-form label-position="top"><el-form-item label="手机号"><el-input v-model="contact.phone" maxlength="11" /></el-form-item><el-form-item label="邮箱"><el-input v-model="contact.email" /></el-form-item><el-button type="primary" :loading="saving" @click="saveContact">保存联系方式</el-button></el-form></article><article><h2>修改密码</h2><p>新密码长度应为 8–72 位，修改后需重新登录。</p><el-form label-position="top"><el-form-item label="当前密码"><el-input v-model="password.currentPassword" type="password" show-password /></el-form-item><el-form-item label="新密码"><el-input v-model="password.newPassword" type="password" show-password /></el-form-item><el-form-item label="确认新密码"><el-input v-model="password.confirmPassword" type="password" show-password /></el-form-item><el-button type="primary" :loading="saving" :disabled="!password.currentPassword || password.newPassword.length < 8 || !password.confirmPassword" @click="savePassword">修改密码</el-button></el-form></article></div><el-divider /><div class="logout-row"><div><b>退出当前账号</b><p>退出后，当前设备将清除登录状态。</p></div><el-button type="danger" plain @click="logout">退出登录</el-button></div></section></div></template>
