<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { addressApi, type Address } from '@/api/services'
const addresses = ref<Address[]>([]); const dialog = ref(false); const editingId = ref<number>(); const saving = ref(false)
const empty = (): Omit<Address, 'id'> => ({ receiverName: '', receiverPhone: '', province: '', city: '', district: '', detailAddress: '', defaultAddress: false }); const form = reactive(empty())
const load = async () => { addresses.value = await addressApi.list() }
const open = (item?: Address) => { editingId.value = item?.id; Object.assign(form, item || empty()); dialog.value = true }
const save = async () => { saving.value = true; try { const payload = { ...form }; if (editingId.value) await addressApi.update(editingId.value, payload); else await addressApi.create(payload); ElMessage.success('地址已保存'); dialog.value = false; await load() } finally { saving.value = false } }
const remove = async (item: Address) => { try { await ElMessageBox.confirm(`确认删除 ${item.receiverName} 的收货地址吗？`, '删除地址', { type: 'warning' }) } catch { return } await addressApi.remove(item.id); ElMessage.success('地址已删除'); await load() }
onMounted(load)
</script>
<template><div class="shell page personal-layout"><aside class="personal-nav"><h3>个人中心</h3><RouterLink to="/profile">个人资料</RouterLink><RouterLink to="/orders">我的订单</RouterLink><RouterLink to="/addresses" class="selected">收货地址</RouterLink><RouterLink to="/account">账户安全</RouterLink></aside><section class="profile-content"><div class="content-heading"><div><h1>收货地址</h1><p>下单时可直接选择已保存的地址。</p></div><el-button type="primary" @click="open()">新增地址</el-button></div><div class="saved-addresses"><article v-for="item in addresses" :key="item.id"><div><b>{{ item.receiverName }}　{{ item.receiverPhone }}</b><p>{{ item.province }} {{ item.city }} {{ item.district }} {{ item.detailAddress }}</p><el-tag v-if="item.defaultAddress" size="small">默认地址</el-tag></div><span><el-button text type="primary" @click="open(item)">编辑</el-button><el-button text type="danger" @click="remove(item)">删除</el-button></span></article><el-empty v-if="!addresses.length" description="还没有收货地址" /></div></section><el-dialog v-model="dialog" :title="editingId ? '编辑收货地址' : '新增收货地址'" width="min(560px, 92vw)"><el-form :model="form" label-width="82px"><div class="form-pair"><el-form-item label="收货人" required><el-input v-model="form.receiverName" /></el-form-item><el-form-item label="手机号" required><el-input v-model="form.receiverPhone" maxlength="11" /></el-form-item></div><div class="form-pair"><el-form-item label="省份" required><el-input v-model="form.province" /></el-form-item><el-form-item label="城市" required><el-input v-model="form.city" /></el-form-item></div><el-form-item label="区县" required><el-input v-model="form.district" /></el-form-item><el-form-item label="详细地址" required><el-input v-model="form.detailAddress" type="textarea" :rows="3" /></el-form-item><el-form-item label="默认地址"><el-switch v-model="form.defaultAddress" /></el-form-item></el-form><template #footer><el-button @click="dialog = false">取消</el-button><el-button type="primary" :loading="saving" :disabled="!form.receiverName || !form.receiverPhone || !form.province || !form.city || !form.district || !form.detailAddress" @click="save">保存</el-button></template></el-dialog></div></template>
