<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { adminApi, type AdminUser } from '@/api/services'
const filters=reactive({keyword:'',role:'',status:undefined as number|undefined});const rows=ref<AdminUser[]>([]);const total=ref(0);const page=ref(1);const loading=ref(false);const detail=ref<AdminUser>();const visible=ref(false)
const load=async()=>{loading.value=true;try{const r=await adminApi.users({...filters,keyword:filters.keyword||undefined,role:filters.role||undefined,page:page.value,size:20});rows.value=r.items;total.value=r.total}finally{loading.value=false}}
const search=()=>{page.value=1;load()};const show=async(id:number)=>{detail.value=await adminApi.user(id);visible.value=true}
const toggle=async(user:AdminUser)=>{await ElMessageBox.confirm(`确认${user.status===1?'禁用':'启用'}用户 ${user.username}？`,'账号状态');await adminApi.changeUserStatus(user.id,user.status===1?0:1);ElMessage.success('状态已更新');load()}
onMounted(load)
</script>
<template><div><div class="admin-page-title"><div><span>ACCOUNT GOVERNANCE</span><h1>用户管理</h1><p>查询买家账号、查看联系方式并控制账号可用状态。</p></div></div><section class="admin-card"><div class="toolbar"><el-input v-model="filters.keyword" clearable placeholder="用户名 / 昵称 / 手机 / 邮箱" @keyup.enter="search"/><el-select v-model="filters.role" clearable placeholder="全部角色"><el-option label="普通用户" value="USER"/><el-option label="管理员" value="ADMIN"/></el-select><el-select v-model="filters.status" clearable placeholder="全部状态"><el-option label="正常" :value="1"/><el-option label="禁用" :value="0"/></el-select><el-button type="primary" @click="search">查询</el-button></div><el-table v-loading="loading" :data="rows"><el-table-column prop="id" label="ID" width="80"/><el-table-column prop="username" label="用户名"/><el-table-column prop="nickname" label="昵称"/><el-table-column prop="phone" label="手机号"/><el-table-column prop="email" label="邮箱"/><el-table-column label="角色" width="100"><template #default="s"><el-tag>{{ s.row.role }}</el-tag></template></el-table-column><el-table-column label="状态" width="90"><template #default="s"><el-tag :type="s.row.status===1?'success':'danger'">{{s.row.status===1?'正常':'禁用'}}</el-tag></template></el-table-column><el-table-column label="操作" width="150"><template #default="s"><el-button link type="primary" @click="show(s.row.id)">详情</el-button><el-button v-if="s.row.role!=='ADMIN'" link :type="s.row.status===1?'danger':'success'" @click="toggle(s.row)">{{s.row.status===1?'禁用':'启用'}}</el-button></template></el-table-column></el-table><div class="admin-pagination"><el-pagination v-model:current-page="page" background layout="total, prev, pager, next" :page-size="20" :total="total" @current-change="load"/></div></section><el-dialog v-model="visible" title="用户详情" width="580px"><el-descriptions v-if="detail" :column="2" border><el-descriptions-item label="用户 ID">{{detail.id}}</el-descriptions-item><el-descriptions-item label="用户名">{{detail.username}}</el-descriptions-item><el-descriptions-item label="昵称">{{detail.nickname||'-'}}</el-descriptions-item><el-descriptions-item label="角色">{{detail.role}}</el-descriptions-item><el-descriptions-item label="手机号">{{detail.phone||'-'}}</el-descriptions-item><el-descriptions-item label="邮箱">{{detail.email||'-'}}</el-descriptions-item><el-descriptions-item label="创建时间" :span="2">{{detail.createdAt||'-'}}</el-descriptions-item></el-descriptions></el-dialog></div></template>
