<script setup lang="ts">
import { onBeforeUnmount, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { Lock, Phone, User } from '@element-plus/icons-vue'
import { ElMessage } from 'element-plus'
import { authApi } from '@/api/services'
import { useSession } from '@/composables/session'

const router = useRouter(); const route = useRoute(); const { setUser } = useSession(); const mode = ref<'login' | 'register'>('login'); const loginMethod = ref<'password' | 'sms'>('password'); const loading = ref(false)
const form = ref({ username: '', password: '', nickname: '', phone: '', email: '' })
const sms = reactive({ phone: '', code: '', mockCode: '' }); const countdown = ref(0); let timer: number | undefined
const startCountdown = (seconds: number) => { countdown.value = seconds; window.clearInterval(timer); timer = window.setInterval(() => { countdown.value -= 1; if (countdown.value <= 0) window.clearInterval(timer) }, 1000) }
const sendCode = async () => { if (!/^1\d{10}$/.test(sms.phone)) return ElMessage.warning('请输入正确的手机号'); const result = await authApi.sendSmsCode(sms.phone, 'login'); sms.mockCode = result.debugCode; sms.code = result.debugCode; startCountdown(result.retryAfterSeconds); ElMessage.success('Mock 验证码已生成并自动填入') }
const finishLogin = (result: Awaited<ReturnType<typeof authApi.login>>) => { localStorage.setItem('dingdong_token', result.token); setUser(result.user); const redirect = typeof route.query.redirect === 'string' ? route.query.redirect : ''; router.replace(result.user.role === 'ADMIN' ? '/admin' : (redirect.startsWith('/') ? redirect : '/')) }
const submit = async () => { loading.value = true; try { if (mode.value === 'login') { const result = loginMethod.value === 'sms' ? await authApi.smsLogin(sms.phone, sms.code) : await authApi.login({ username: form.value.username, password: form.value.password }); finishLogin(result) } else { await authApi.register(form.value); ElMessage.success('注册成功，请登录'); mode.value = 'login' } } finally { loading.value = false } }
onBeforeUnmount(() => window.clearInterval(timer))
</script>
<template><div class="auth-page"><section class="auth-aside"><RouterLink to="/" class="brand"><span class="brand-mark"><img src="/DingDongLogo.png" alt="叮咚商城" /></span><span>叮咚商城<small>好物准时到</small></span></RouterLink><div><span>从发现好物到安心收货</span><h1>每一次下单，<br />都有可靠回应。</h1><p>登录后即可管理购物车、地址和订单，继续你的品质生活。</p></div></section><section class="auth-panel"><el-card shadow="never" class="auth-card"><div class="auth-tabs"><button :class="{ active: mode === 'login' }" @click="mode = 'login'">登录</button><button :class="{ active: mode === 'register' }" @click="mode = 'register'">注册</button></div><p class="auth-lead">{{ mode === 'login' ? '欢迎回来，请登录你的账户' : '创建账户，开启叮咚购物之旅' }}</p><el-segmented v-if="mode === 'login'" v-model="loginMethod" :options="[{ label: '密码登录', value: 'password' }, { label: '短信登录', value: 'sms' }]" style="width:100%;margin-bottom:18px" /><el-form :model="form" label-position="top" @submit.prevent="submit"><template v-if="mode === 'register' || loginMethod === 'password'"><el-form-item label="用户名" required><el-input v-model="form.username" :prefix-icon="User" placeholder="请输入用户名" /></el-form-item><el-form-item v-if="mode === 'register'" label="昵称"><el-input v-model="form.nickname" placeholder="例如：叮咚用户" /></el-form-item><el-form-item v-if="mode === 'register'" label="手机号"><el-input v-model="form.phone" placeholder="选填" /></el-form-item><el-form-item v-if="mode === 'register'" label="邮箱"><el-input v-model="form.email" placeholder="选填" /></el-form-item><el-form-item label="密码" required><el-input v-model="form.password" :prefix-icon="Lock" type="password" show-password placeholder="请输入密码" /></el-form-item></template><template v-else><el-form-item label="手机号" required><el-input v-model="sms.phone" :prefix-icon="Phone" maxlength="11" placeholder="请输入手机号" /></el-form-item><el-form-item label="短信验证码" required><el-input v-model="sms.code" maxlength="6" placeholder="六位验证码"><template #append><el-button :disabled="countdown > 0" @click="sendCode">{{ countdown > 0 ? `${countdown}s` : '获取验证码' }}</el-button></template></el-input></el-form-item><el-alert v-if="sms.mockCode" type="warning" :closable="false" show-icon :title="`第三方短信认证尚未通过，本次 Mock 验证码：${sms.mockCode}`" /></template><el-button type="primary" size="large" native-type="submit" :loading="loading" class="auth-submit">{{ mode === 'login' ? '登录' : '注册账户' }}</el-button></el-form><p v-if="mode === 'login'" class="auth-note">本地演示管理员：admin / password</p></el-card></section></div></template>
