<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { Delete, ShoppingCart } from '@element-plus/icons-vue'
import { cartApi, type CartItem } from '@/api/services'
import { useRouter } from 'vue-router'
const router = useRouter(); const cart = ref<CartItem[]>([]); const loading = ref(true); const total = computed(() => cart.value.filter((item) => item.selected).reduce((sum, item) => sum + item.unitPrice * item.quantity, 0)); const selectedCount = computed(() => cart.value.filter((item) => item.selected).length); const price = (value: number) => Number(value).toFixed(2)
const load = async () => { loading.value = true; try { cart.value = await cartApi.list() } finally { loading.value = false } }; const update = async (item: CartItem) => { await cartApi.update(item.id, { quantity: item.quantity, selected: item.selected }) }; const remove = async (id: number) => { await cartApi.remove(id); cart.value = cart.value.filter((item) => item.id !== id) }; const toggleAll = async (value: boolean | string | number) => { await Promise.all(cart.value.map(async (item) => { item.selected = Boolean(value); await update(item) })) }; onMounted(load)
</script>
<template><div class="shell page"><div class="cart-title"><div><span>购物车</span><h1>确认你的心动好物</h1></div><RouterLink to="/products">继续购物</RouterLink></div><el-skeleton :loading="loading" animated :rows="6"><template #default><div v-if="cart.length" class="cart-layout"><section class="cart-list"><div class="cart-head"><el-checkbox :model-value="selectedCount === cart.length" @change="toggleAll">全选</el-checkbox><span>商品信息</span><span>单价</span><span>数量</span><span>小计</span><span>操作</span></div><article v-for="item in cart" :key="item.id" class="cart-row"><el-checkbox v-model="item.selected" @change="update(item)" /><img :src="item.mainImageUrl || 'https://placehold.co/200x200/eaf3ff/1677ff?text=DingDong'" :alt="item.productTitle" /><div><b>{{ item.productTitle }}</b><p>{{ item.specJson }}</p></div><b>¥{{ price(item.unitPrice) }}</b><el-input-number v-model="item.quantity" :min="1" :max="Math.min(item.availableStock || 99, 99)" size="small" @change="update(item)" /><strong>¥{{ price(item.unitPrice * item.quantity) }}</strong><el-button text type="danger" :icon="Delete" @click="remove(item.id)">删除</el-button></article></section><aside class="summary-card"><h3>订单摘要</h3><p><span>已选商品</span><b>{{ selectedCount }} 件</b></p><p><span>商品金额</span><b>¥{{ price(total) }}</b></p><p>运费<b>免运费</b></p><div><span>合计</span><strong>¥{{ price(total) }}</strong></div><el-button type="primary" size="large" :disabled="!selectedCount" @click="router.push('/checkout')">去结算</el-button></aside></div><el-empty v-else :image-size="100" description="购物车还是空的"><RouterLink to="/products"><el-button type="primary" :icon="ShoppingCart">去挑选商品</el-button></RouterLink></el-empty></template></el-skeleton></div></template>
