<script setup lang="ts">
import { computed, ref } from 'vue'
import { Delete, ShoppingCart } from '@element-plus/icons-vue'
import { products, formatPrice } from '@/mock'
import { useRouter } from 'vue-router'
const router = useRouter(); const cart = ref(products.slice(0, 3).map((product, index) => ({ product, quantity: index + 1, selected: true }))); const total = computed(() => cart.value.filter((item) => item.selected).reduce((sum, item) => sum + item.product.price * item.quantity, 0)); const selectedCount = computed(() => cart.value.filter((item) => item.selected).length)
const toggleAll = (value: boolean | string | number) => cart.value.forEach((item) => { item.selected = Boolean(value) })
</script>
<template><div class="shell page"><div class="cart-title"><div><span>购物车</span><h1>确认你的心动好物</h1></div><RouterLink to="/products">继续购物</RouterLink></div><div v-if="cart.length" class="cart-layout"><section class="cart-list"><div class="cart-head"><el-checkbox :model-value="selectedCount === cart.length" @change="toggleAll">全选</el-checkbox><span>商品信息</span><span>单价</span><span>数量</span><span>小计</span><span>操作</span></div><article v-for="item in cart" :key="item.product.id" class="cart-row"><el-checkbox v-model="item.selected" /><img :src="item.product.image" :alt="item.product.name" /><div><RouterLink :to="`/product/${item.product.id}`">{{ item.product.name }}</RouterLink><p>{{ item.product.specs.slice(0, 2).join(' · ') }}</p></div><b>¥{{ formatPrice(item.product.price) }}</b><el-input-number v-model="item.quantity" :min="1" :max="10" size="small" /><strong>¥{{ formatPrice(item.product.price * item.quantity) }}</strong><el-button text type="danger" :icon="Delete" @click="cart = cart.filter((entry) => entry.product.id !== item.product.id)">删除</el-button></article></section><aside class="summary-card"><h3>订单摘要</h3><p><span>已选商品</span><b>{{ selectedCount }} 件</b></p><p><span>商品金额</span><b>¥{{ formatPrice(total) }}</b></p><p>运费<b>免运费</b></p><div><span>合计</span><strong>¥{{ formatPrice(total) }}</strong></div><el-button type="primary" size="large" :disabled="!selectedCount" @click="router.push('/checkout')">去结算</el-button></aside></div><el-empty v-else :image-size="100" description="购物车还是空的"><RouterLink to="/products"><el-button type="primary" :icon="ShoppingCart">去挑选商品</el-button></RouterLink></el-empty></div></template>
