<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import { addressApi, cartApi, orderApi, type Address, type CartItem } from '@/api/services'
const route = useRoute(); const router = useRouter(); const addresses = ref<Address[]>([]); const items = ref<CartItem[]>([]); const addressId = ref<number>(); const loading = ref(true); const submitting = ref(false)
const checkoutItems = computed(() => { const id = Number(route.query.cartItemId); return id ? items.value.filter((item) => item.id === id) : items.value.filter((item) => item.selected) }); const total = computed(() => checkoutItems.value.reduce((sum, item) => sum + item.unitPrice * item.quantity, 0)); const price = (value: number) => Number(value).toFixed(2)
const submit = async () => { if (!addressId.value || !checkoutItems.value.length) return; submitting.value = true; try { const order = await orderApi.create({ addressId: addressId.value, cartItemIds: checkoutItems.value.map((item) => item.id) }); router.push({ path: '/payment', query: { orderNo: order.orderNo, amount: order.totalAmount } }) } finally { submitting.value = false } }
onMounted(async () => { try { const [addressData, cartData] = await Promise.all([addressApi.list(), cartApi.list()]); addresses.value = addressData; items.value = cartData; addressId.value = addressData.find((item) => item.defaultAddress)?.id || addressData[0]?.id; if (!checkoutItems.value.length) ElMessage.warning('没有可结算的商品') } finally { loading.value = false } })
</script>
<template><div class="shell page"><div class="checkout-steps"><span class="done">1. 确认订单</span><i></i><span>2. 模拟支付</span><i></i><span>3. 完成</span></div><h1 class="checkout-title">确认订单信息</h1><el-skeleton :loading="loading" animated :rows="10"><template #default><section class="checkout-box"><div class="checkout-heading"><h2>收货地址</h2><RouterLink to="/addresses">管理收货地址</RouterLink></div><div class="address-list"><article v-for="address in addresses" :key="address.id" :class="{ selected: addressId === address.id }" @click="addressId = address.id"><b>{{ address.receiverName }}　{{ address.receiverPhone }}</b><p>{{ address.province }} {{ address.city }} {{ address.district }} {{ address.detailAddress }}</p><span v-if="address.defaultAddress">默认地址</span></article><el-empty v-if="!addresses.length" description="暂无收货地址"><RouterLink to="/addresses"><el-button type="primary">新增收货地址</el-button></RouterLink></el-empty></div></section><section class="checkout-box"><h2>商品清单</h2><article v-for="item in checkoutItems" :key="item.id" class="checkout-product"><img :src="item.mainImageUrl || 'https://placehold.co/200x200/eaf3ff/1677ff?text=DingDong'" :alt="item.productTitle" /><div><b>{{ item.productTitle }}</b><p>{{ item.specJson }}</p></div><span>¥{{ price(item.unitPrice) }} × {{ item.quantity }}</span><strong>¥{{ price(item.unitPrice * item.quantity) }}</strong></article><el-empty v-if="!checkoutItems.length" description="暂无可结算商品" /></section><section class="checkout-total"><h2>应付金额：<strong>¥{{ price(total) }}</strong></h2><el-button type="primary" size="large" :loading="submitting" :disabled="!addressId || !checkoutItems.length" @click="submit">提交订单</el-button></section></template></el-skeleton></div></template>
