<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { ArrowRight, Lightning, Service, Van, CircleCheck } from '@element-plus/icons-vue'
import { ElMessage } from 'element-plus'
import { catalogApi, cartApi, type Category, type ProductListItem } from '@/api/services'
import ProductCard from '@/components/ProductCard.vue'
const categories = ref<Category[]>([]); const products = ref<ProductListItem[]>([]); const loading = ref(true)
const add = async (product: ProductListItem) => { try { const detail = await catalogApi.product(product.id); const sku = detail.skus.find((item) => item.status === 1); if (!sku) return ElMessage.warning('商品暂无可售规格'); await cartApi.add(sku.id, 1); ElMessage.success('已加入购物车') } catch { /* handled centrally */ } }
onMounted(async () => { try { const [categoryResult, productResult] = await Promise.all([catalogApi.categories(), catalogApi.products({ page: 1, size: 12, sort: 'sales' })]); categories.value = categoryResult; products.value = productResult.items } finally { loading.value = false } })
</script>
<template><div><section class="shell hero-wrap"><aside class="category-panel"><h3>全部商品分类</h3><RouterLink v-for="category in categories" :key="category.id" :to="{ path: '/products', query: { categoryId: category.id } }">{{ category.name }}<el-icon><ArrowRight /></el-icon></RouterLink><el-skeleton v-if="!categories.length" :rows="6" animated /></aside><div class="hero"><div class="hero-copy"><span>夏日清凉季</span><h1>精选好物，<br />准时叮咚到家</h1><p>甄选品质商品，享受清爽夏日价。</p><RouterLink to="/products"><el-button type="primary" size="large">立即选购 <el-icon><ArrowRight /></el-icon></el-button></RouterLink></div><div class="hero-art"><div class="hero-orb orb-one"></div><div class="hero-orb orb-two"></div><img src="https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=1000&q=85" alt="夏日精选商品" /></div></div></section><section class="shell benefits"><span><el-icon><Lightning /></el-icon>限时好价</span><span><el-icon><CircleCheck /></el-icon>正品保障</span><span><el-icon><Van /></el-icon>极速配送</span><span><el-icon><Service /></el-icon>贴心售后</span></section><section id="hot" class="shell section"><div class="section-title"><div><span>热销好物</span><h2>大家都在买</h2></div><RouterLink to="/products">查看全部 <el-icon><ArrowRight /></el-icon></RouterLink></div><el-skeleton :loading="loading" animated :count="1"><template #template><div class="product-grid"><el-skeleton-item v-for="item in 4" :key="item" variant="rect" style="height: 310px" /></div></template><template #default><div class="product-grid"><ProductCard v-for="product in products.slice(0, 4)" :key="product.id" :product="product" @add="add" /></div></template></el-skeleton></section><section id="recommend" class="shell section"><div class="section-title"><div><span>商城运营精选</span><h2>运营精选</h2></div><RouterLink to="/products">更多商品 <el-icon><ArrowRight /></el-icon></RouterLink></div><div class="product-grid"><ProductCard v-for="product in products.slice(4, 12)" :key="product.id" :product="product" @add="add" /></div></section></div></template>
