<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { CircleCheckFilled, CreditCard } from '@element-plus/icons-vue'
import { ElMessage } from 'element-plus'
import { orderApi, paymentApi } from '@/api/services'
const route = useRoute(); const router = useRouter(); const paymentNo = ref(''); const paid = ref(false); const loading = ref(false); const method = ref<'wechat' | 'alipay'>('wechat'); const orderNo = String(route.query.orderNo || ''); const amount = Number(route.query.amount || 0).toFixed(2)
const verifyPaid = async () => { for (let i = 0; i < 10; i += 1) { const order = await orderApi.detail(orderNo); if (order.status === 'PAID') return true; await new Promise((resolve) => setTimeout(resolve, 350)) } return false }
const pay = async () => { loading.value = true; try { await paymentApi.simulate(paymentNo.value, true); if (!await verifyPaid()) { ElMessage.warning('支付已受理，订单状态同步中，请稍后在订单页查看'); return router.push('/orders') } paid.value = true } finally { loading.value = false } }
onMounted(async () => { if (!orderNo) return router.replace('/orders'); const order = await orderApi.detail(orderNo); if (order.status === 'PAID') { paid.value = true; return } if (order.status !== 'PENDING_PAYMENT') { ElMessage.warning('当前订单不可支付'); return router.replace('/orders') } const payment = await paymentApi.create(orderNo); paymentNo.value = payment.paymentNo; if (payment.status === 'SUCCESS') paid.value = await verifyPaid() })
</script>
<template><div class="payment-page"><section v-if="!paid" class="payment-card"><div class="payment-status"><el-icon><CreditCard /></el-icon><div><span>订单提交成功，请完成模拟支付</span><h1>¥ {{ amount }}</h1><p>订单号：{{ orderNo }}　请在 30 分钟内完成支付</p></div></div><el-divider /><h2>选择模拟支付方式</h2><div class="pay-options"><article :class="{ selected: method === 'wechat' }" @click="method = 'wechat'"><span class="pay-logo wechat">微</span><b>模拟微信支付</b><i v-if="method === 'wechat'">已选择</i></article><article :class="{ selected: method === 'alipay' }" @click="method = 'alipay'"><span class="pay-logo alipay">支</span><b>模拟支付宝支付</b><i v-if="method === 'alipay'">已选择</i></article></div><el-alert type="info" :closable="false" show-icon title="开发环境模拟支付，不会发生真实资金扣款。" /><el-button type="primary" size="large" class="pay-submit" :loading="loading" :disabled="!paymentNo" @click="pay">确认付款</el-button></section><section v-else class="payment-card payment-result"><el-icon><CircleCheckFilled /></el-icon><h1>支付成功</h1><p>订单状态已更新，可在我的订单中查看。</p><el-button type="primary" @click="router.push('/orders')">查看我的订单</el-button></section></div></template>
