<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ShoppingCart } from '@element-plus/icons-vue'
import { ElMessage } from 'element-plus'
import { cartApi, catalogApi, type ProductDetail, type Sku } from '@/api/services'
import { useCartSummary } from '@/composables/cart'
const route = useRoute(); const router = useRouter(); const product = ref<ProductDetail>(); const selectedSku = ref<Sku>(); const count = ref(1); const loading = ref(true); const activeTab = ref<'detail' | 'spec' | 'service'>('detail'); const { refreshCartCount } = useCartSummary()
const parsedSpecs = computed<Record<string, unknown>>(() => { try { return selectedSku.value?.specJson ? JSON.parse(selectedSku.value.specJson) : {} } catch { return {} } }); const specs = computed(() => Object.values(parsedSpecs.value).join(' · ')); const price = computed(() => Number(selectedSku.value?.price || product.value?.minPrice || 0).toFixed(2))
const selectSku = (sku: Sku) => { selectedSku.value = sku; count.value = 1 }
const requireLogin = () => { if (localStorage.getItem('dingdong_token')) return true; router.push({ path: '/auth', query: { redirect: route.fullPath } }); return false }
const add = async () => { if (!selectedSku.value || !requireLogin()) return; await cartApi.add(selectedSku.value.id, count.value); await refreshCartCount(); ElMessage.success('已加入购物车') }
const buy = async () => { if (!selectedSku.value || !requireLogin()) return; const item = await cartApi.add(selectedSku.value.id, count.value); await refreshCartCount(); router.push({ path: '/checkout', query: { cartItemId: item.id } }) }
onMounted(async () => { try { product.value = await catalogApi.product(Number(route.params.id)); selectedSku.value = product.value.skus.find((item) => item.status === 1 && item.availableStock > 0) } finally { loading.value = false } })
</script>
<template><div class="shell page"><el-skeleton :loading="loading" animated :rows="10"><template #default><template v-if="product"><el-breadcrumb separator="/"><el-breadcrumb-item to="/">首页</el-breadcrumb-item><el-breadcrumb-item to="/products">全部商品</el-breadcrumb-item><el-breadcrumb-item>{{ product.title }}</el-breadcrumb-item></el-breadcrumb><section class="detail-card"><div class="gallery"><div class="main-photo"><img :src="product.mainImageUrl || 'https://placehold.co/800x800/eaf3ff/1677ff?text=DingDong'" :alt="product.title" /></div></div><div class="detail-info"><h1>{{ product.title }}</h1><p class="subtitle">{{ product.subtitle }}</p><div class="price-panel"><span>叮咚价</span><strong>¥{{ price }}</strong><small>库存及价格以提交订单时为准</small></div><div class="detail-line"><span>配送</span><b>由叮咚商城发货</b><em>商品现货以实时库存为准</em></div><div class="detail-line spec-line"><span>规格</span><div><el-button v-for="sku in product.skus.filter((item) => item.status === 1)" :key="sku.id" :type="selectedSku?.id === sku.id ? 'primary' : 'default'" :disabled="sku.availableStock < 1" plain @click="selectSku(sku)">{{ Object.values(JSON.parse(sku.specJson)).join(' · ') }}</el-button></div></div><div class="detail-line"><span>数量</span><el-input-number v-model="count" :min="1" :max="Math.min(selectedSku?.availableStock || 1, 99)" :disabled="!selectedSku" /></div><div class="actions"><el-button type="primary" size="large" :disabled="!selectedSku" @click="add" :icon="ShoppingCart">加入购物车</el-button><el-button size="large" class="buy-button" :disabled="!selectedSku" @click="buy">立即购买</el-button></div><div class="detail-tools"><span v-if="selectedSku">库存 {{ selectedSku.availableStock }} 件</span><span>支持订单查询与确认收货</span></div></div></section><section class="detail-description"><aside><button :class="{ active: activeTab === 'detail' }" @click="activeTab = 'detail'">商品详情</button><button :class="{ active: activeTab === 'spec' }" @click="activeTab = 'spec'">规格参数</button><button :class="{ active: activeTab === 'service' }" @click="activeTab = 'service'">售后保障</button></aside><article v-if="activeTab === 'detail'"><h2>商品介绍</h2><p>{{ product.description || '暂未提供商品详情描述。' }}</p><p v-if="specs">当前选择：{{ specs }}</p></article><article v-else-if="activeTab === 'spec'"><h2>规格参数</h2><el-descriptions v-if="Object.keys(parsedSpecs).length" :column="1" border><el-descriptions-item v-for="(value, key) in parsedSpecs" :key="key" :label="String(key)">{{ value }}</el-descriptions-item></el-descriptions><el-empty v-else description="该规格暂无参数" /></article><article v-else><h2>售后保障</h2><p>如商品出现质量问题，请保留商品及订单凭证并联系客服处理。退换申请需符合商品完好、配件齐全等条件；具体结果以客服审核为准。</p><p>订单发货后可在“我的订单”查看物流信息，收货后请及时确认收货。</p></article></section></template><el-empty v-else description="商品不存在或已下架"><RouterLink to="/products"><el-button type="primary">返回商品列表</el-button></RouterLink></el-empty></template></el-skeleton></div></template>
