<script setup lang="ts">
import { computed, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { Star, Share, ShoppingCart } from '@element-plus/icons-vue'
import { products, formatPrice } from '@/mock'
const route = useRoute(); const router = useRouter(); const product = computed(() => products.find((item) => item.id === Number(route.params.id)) || products[0]); const count = ref(1); const picked = ref(product.value.specs[0]); const message = ref('')
const buyNow = () => router.push('/checkout')
</script>
<template><div class="shell page"><el-breadcrumb separator="/"><el-breadcrumb-item to="/">首页</el-breadcrumb-item><el-breadcrumb-item to="/products">全部商品</el-breadcrumb-item><el-breadcrumb-item>{{ product.name }}</el-breadcrumb-item></el-breadcrumb><section class="detail-card"><div class="gallery"><div class="main-photo"><img :src="product.image" :alt="product.name" /></div><div class="thumbs"><img :src="product.image" :alt="product.name" /><img :src="product.image" :alt="product.name" /></div></div><div class="detail-info"><h1>{{ product.name }}</h1><p class="subtitle">{{ product.subtitle }}</p><div class="price-panel"><span>叮咚价</span><strong>¥{{ formatPrice(product.price) }}</strong><del v-if="product.oldPrice">¥{{ formatPrice(product.oldPrice) }}</del><small>已售 {{ product.sales.toLocaleString() }} 件</small></div><div class="detail-line"><span>配送</span><b>北京 朝阳区</b><em>现货，预计明日送达</em></div><div class="detail-line spec-line"><span>规格</span><div><el-button v-for="spec in product.specs" :key="spec" :type="picked === spec ? 'primary' : 'default'" plain @click="picked = spec">{{ spec }}</el-button></div></div><div class="detail-line"><span>数量</span><el-input-number v-model="count" :min="1" :max="Math.min(product.stock, 10)" /></div><div class="actions"><el-button type="primary" size="large" @click="message = '已加入购物车'" :icon="ShoppingCart">加入购物车</el-button><el-button size="large" class="buy-button" @click="buyNow">立即购买</el-button></div><div class="detail-tools"><span><el-icon><Star /></el-icon> 收藏</span><span><el-icon><Share /></el-icon> 分享</span><span>库存 {{ product.stock }} 件</span></div></div></section><section class="detail-description"><aside><b>商品详情</b><a>规格参数</a><a>用户评价</a><a>售后保障</a></aside><article><h2>好物，值得细看</h2><p>严选材质与可靠工艺，为日常生活提供恰到好处的品质体验。商品实际信息以下单页面为准。</p><img :src="product.image" :alt="product.name" /></article></section><el-alert v-if="message" class="floating-notice" type="success" :closable="true" @close="message = ''" show-icon>{{ message }}</el-alert></div></template>
