<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { Star, Share, ShoppingCart } from '@element-plus/icons-vue'
import { ElMessage } from 'element-plus'
import { cartApi, catalogApi, type ProductDetail, type Sku } from '@/api/services'
const route = useRoute(); const router = useRouter(); const product = ref<ProductDetail>(); const selectedSku = ref<Sku>(); const count = ref(1); const loading = ref(true)
const specs = computed(() => selectedSku.value?.specJson ? Object.values(JSON.parse(selectedSku.value.specJson)).join(' · ') : '')
const price = computed(() => Number(selectedSku.value?.price || product.value?.minPrice || 0).toFixed(2))
const selectSku = (sku: Sku) => { selectedSku.value = sku; count.value = 1 }
const add = async () => { if (!selectedSku.value) return; await cartApi.add(selectedSku.value.id, count.value); ElMessage.success('已加入购物车') }
const buy = async () => { await add(); router.push('/checkout') }
onMounted(async () => { try { product.value = await catalogApi.product(Number(route.params.id)); selectedSku.value = product.value.skus.find((item) => item.status === 1) } finally { loading.value = false } })
</script>
<template><div class="shell page"><el-skeleton :loading="loading" animated :rows="10"><template #default><template v-if="product"><el-breadcrumb separator="/"><el-breadcrumb-item to="/">首页</el-breadcrumb-item><el-breadcrumb-item to="/products">全部商品</el-breadcrumb-item><el-breadcrumb-item>{{ product.title }}</el-breadcrumb-item></el-breadcrumb><section class="detail-card"><div class="gallery"><div class="main-photo"><img :src="product.mainImageUrl || 'https://placehold.co/800x800/eaf3ff/1677ff?text=DingDong'" :alt="product.title" /></div></div><div class="detail-info"><h1>{{ product.title }}</h1><p class="subtitle">{{ product.subtitle }}</p><div class="price-panel"><span>叮咚价</span><strong>¥{{ price }}</strong><small>库存及价格以提交订单时为准</small></div><div class="detail-line"><span>配送</span><b>由叮咚商城发货</b><em>商品现货以实时库存为准</em></div><div class="detail-line spec-line"><span>规格</span><div><el-button v-for="sku in product.skus.filter((item) => item.status === 1)" :key="sku.id" :type="selectedSku?.id === sku.id ? 'primary' : 'default'" plain @click="selectSku(sku)">{{ Object.values(JSON.parse(sku.specJson)).join(' · ') }}</el-button></div></div><div class="detail-line"><span>数量</span><el-input-number v-model="count" :min="1" :max="Math.min(selectedSku?.availableStock || 1, 99)" :disabled="!selectedSku" /></div><div class="actions"><el-button type="primary" size="large" :loading="loading" :disabled="!selectedSku" @click="add" :icon="ShoppingCart">加入购物车</el-button><el-button size="large" class="buy-button" :disabled="!selectedSku" @click="buy">立即购买</el-button></div><div class="detail-tools"><span><el-icon><Star /></el-icon> 收藏</span><span><el-icon><Share /></el-icon> 分享</span><span v-if="selectedSku">库存 {{ selectedSku.availableStock }} 件</span></div></div></section><section class="detail-description"><aside><b>商品详情</b><a>规格参数</a><a>售后保障</a></aside><article><h2>商品介绍</h2><p>{{ product.description || '暂未提供商品详情描述。' }}</p><p v-if="specs">当前选择：{{ specs }}</p></article></section></template><el-empty v-else description="商品不存在或已下架"><RouterLink to="/products"><el-button type="primary">返回商品列表</el-button></RouterLink></el-empty></template></el-skeleton></div></template>
