<script setup lang="ts">
import { onMounted, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import { ElMessage } from 'element-plus'
import { catalogApi, cartApi, type Category, type ProductListItem } from '@/api/services'
import ProductCard from '@/components/ProductCard.vue'
const route = useRoute(); const categories = ref<Category[]>([]); const products = ref<ProductListItem[]>([]); const total = ref(0); const page = ref(1); const loading = ref(false); const categoryId = ref<number | undefined>(Number(route.query.categoryId) || undefined); const sort = ref('newest')
const load = async () => { loading.value = true; try { const result = await catalogApi.products({ keyword: route.query.q || undefined, categoryId: categoryId.value, sort: sort.value, page: page.value, size: 20 }); products.value = result.items; total.value = result.total } finally { loading.value = false } }
const add = async (product: ProductListItem) => { try { const detail = await catalogApi.product(product.id); const sku = detail.skus.find((item) => item.status === 1); if (!sku) return ElMessage.warning('商品暂无可售规格'); await cartApi.add(sku.id, 1); ElMessage.success('已加入购物车') } catch { /* interceptor displays error */ } }
onMounted(async () => { categories.value = await catalogApi.categories(); await load() }); watch([categoryId, sort, page], load)
</script>
<template><div class="shell page"><el-breadcrumb separator="/"><el-breadcrumb-item :to="{ path: '/' }">首页</el-breadcrumb-item><el-breadcrumb-item>全部商品</el-breadcrumb-item></el-breadcrumb><div class="listing-head"><div><span>叮咚精选</span><h1>发现值得买的好物</h1><p>商品价格与库存以实时接口数据为准。</p></div></div><section class="filter-box"><div><strong>商品分类</strong><el-radio-group v-model="categoryId"><el-radio-button :label="undefined">全部</el-radio-button><el-radio-button v-for="item in categories" :key="item.id" :label="item.id">{{ item.name }}</el-radio-button></el-radio-group></div><div><strong>排序方式</strong><el-radio-group v-model="sort"><el-radio-button label="newest">上新</el-radio-button><el-radio-button label="sales">销量</el-radio-button><el-radio-button label="price-asc">价格从低到高</el-radio-button><el-radio-button label="price-desc">价格从高到低</el-radio-button></el-radio-group></div></section><div class="listing-bar"><span>为你找到 <b>{{ total }}</b> 件商品</span></div><el-skeleton :loading="loading" animated :count="4"><template #template><div class="product-grid"><el-skeleton-item v-for="item in 4" :key="item" variant="rect" style="height: 310px" /></div></template><template #default><div class="product-grid"><ProductCard v-for="product in products" :key="product.id" :product="product" @add="add" /></div><el-empty v-if="!products.length" description="暂无符合条件的商品" /></template></el-skeleton><div class="pager"><el-pagination v-model:current-page="page" background layout="prev, pager, next" :total="total" :page-size="20" /></div></div></template>
