USE dingdong_order;
CREATE TABLE IF NOT EXISTS mall_order (
 id BIGINT NOT NULL AUTO_INCREMENT,order_no VARCHAR(32) NOT NULL,user_id BIGINT NOT NULL,receiver_name VARCHAR(32) NOT NULL,receiver_phone VARCHAR(16) NOT NULL,receiver_address VARCHAR(256) NOT NULL,total_amount DECIMAL(12,2) NOT NULL,status VARCHAR(32) NOT NULL,carrier VARCHAR(64) NULL,tracking_no VARCHAR(64) NULL,shipped_at DATETIME NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY(id),UNIQUE KEY uk_mall_order_no(order_no),KEY idx_mall_order_user(user_id,id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS order_status_log (
 id BIGINT NOT NULL AUTO_INCREMENT,order_id BIGINT NOT NULL,from_status VARCHAR(32) NULL,to_status VARCHAR(32) NOT NULL,operator_type VARCHAR(32) NOT NULL,operator_id BIGINT NULL,remark VARCHAR(255) NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY(id),KEY idx_order_status_log_order(order_id,id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS order_outbox (
 id BIGINT NOT NULL AUTO_INCREMENT,event_type VARCHAR(64) NOT NULL,order_no VARCHAR(32) NOT NULL,status VARCHAR(16) NOT NULL DEFAULT 'PENDING',retry_count INT NOT NULL DEFAULT 0,last_error VARCHAR(512) NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,sent_at DATETIME NULL,
 PRIMARY KEY(id),KEY idx_order_outbox_pending(status,id),KEY idx_order_outbox_order(order_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS order_item (
 id BIGINT NOT NULL AUTO_INCREMENT,order_id BIGINT NOT NULL,sku_id BIGINT NOT NULL,sku_code VARCHAR(64) NOT NULL,product_title VARCHAR(128) NOT NULL,product_image_url VARCHAR(512) NULL,spec_json VARCHAR(1000) NOT NULL,unit_price DECIMAL(12,2) NOT NULL,quantity INT NOT NULL,total_amount DECIMAL(12,2) NOT NULL,
 PRIMARY KEY(id),KEY idx_order_item_order(order_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS order_request (
 id BIGINT NOT NULL AUTO_INCREMENT,user_id BIGINT NOT NULL,request_id VARCHAR(64) NOT NULL,order_no VARCHAR(32) NOT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY(id),UNIQUE KEY uk_order_request_user(user_id,request_id),UNIQUE KEY uk_order_request_no(order_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
